"DefaultColors"
{
	"ColorPanel1"
	{
		"ControlName"		"Panel"
		"xpos"		"90"
		"ypos"		"25"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:0 g:0 b:0"
	}

	"ColorPanel2"
	{
		"ControlName"		"Panel"
		"xpos"		"135"
		"ypos"		"25"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:30 g:30 b:30"
	}

	"ColorPanel3"
	{
		"ControlName"		"Panel"
		"xpos"		"180"
		"ypos"		"25"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:45 g:49 b:40"
	}
	"ColorPanel4"
	{
		"ControlName"		"Panel"
		"xpos"		"225"
		"ypos"		"25"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:62 g:70 b:55"
	}
	"ColorPanel5"
	{
		"ControlName"		"Panel"
		"xpos"		"270"
		"ypos"		"25"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:76 g:88 b:68"
	}
	"ColorPanel6"
	{
		"ControlName"		"Panel"
		"xpos"		"90"
		"ypos"		"70"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:100 g:120 b:100"
	}
	"ColorPanel7"
	{
		"ControlName"		"Panel"
		"xpos"		"135"
		"ypos"		"70"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:136 g:145 b:128"
	}
	"ColorPanel8"
	{
		"ControlName"		"Panel"
		"xpos"		"180"
		"ypos"		"70"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:160 g:170 b:149"
	}
	"ColorPanel9"
	{
		"ControlName"		"Panel"
		"xpos"		"225"
		"ypos"		"70"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:216 g:222 b:211"
	}
	"ColorPanel10"
	{
		"ControlName"		"Panel"
		"xpos"		"270"
		"ypos"		"70"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:255 g:255 b:255"
	}
	"ColorPanel11"
	{
		"ControlName"		"Panel"
		"xpos"		"90"
		"ypos"		"115"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:149 g:136 b:49"
	}
	"ColorPanel12"
	{
		"ControlName"		"Panel"
		"xpos"		"135"
		"ypos"		"115"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"tooltiptext" "r:196 g:181 b:80"
	}

}