#
#
# Common Directories for CMake
#
#
set(LIBCOMMON		${ROOT_DIR}/lib/common/${PLATFORM_SUBDIR})
set(LIBPUBLIC		${ROOT_DIR}/lib/public/${PLATFORM_DIR})
set(THIRDPARTY_DIR 	${ROOT_DIR}/thirdparty)

set(PUBLIC_INCLUDE	${ROOT_DIR}/public)
set(COMMON_INCLUDE 	${ROOT_DIR}/common)
set(TIER0_INCLUDE	${PUBLIC_INCLUDE}/tier0)
set(TIER1_INCLUDE	${PUBLIC_INCLUDE}/tier1)
set(TIER2_INCLUDE	${PUBLIC_INCLUDE}/tier2)
set(TIER3_INCLUDE	${PUBLIC_INCLUDE}/tier3)
set(TIER4_INCLUDE	${PUBLIC_INCLUDE}/tier4)
set(APPSYSTEM_INCLUDE	${PUBLIC_INCLUDE}/appsystem)
set(TOGL_INCLUDE	${PUBLIC_INCLUDE}/togl)

# For LZMA
set(LZMA_INCLUDE	${COMMON_INCLUDE}/lzma)
set(LZMA_SRCS		${THIRDPARTY_DIR}/lzma)

link_directories(${LIBCOMMON} ${LIBPUBLIC})
include_directories(${PUBLIC_INCLUDE} ${COMMON_INCLUDE} ${TIER1_INCLUDE} ${TIER0_INCLUDE})
