#
# Basically a giant file with all of the client sources in it.
# Basically have to do this because the glob would just grab everything and presumably lead to many issues
#
set(CLIENT_BASE_FILES
				${ROOT_DIR}/vgui2/game_controls/FloatSlider.cpp
				hl2/C_Func_Monitor.cpp
				geiger.cpp
				history_resource.cpp
				hud_weapon.cpp
				train.cpp
				${ROOT_DIR}/game/shared/weapon_parse_default.cpp
				${ROOT_DIR}/game/shared/Achievement_SaveRestore.cpp
				${ROOT_DIR}/game/shared/Achievement_SaveRestore.h
				${ROOT_DIR}/game/shared/AchievementMgr.cpp
				${ROOT_DIR}/game/shared/AchievementMgr.h
				${ROOT_DIR}/game/shared/achievements_hlx.cpp
				achievement_notification_panel.cpp
				achievement_notification_panel.h
				${ROOT_DIR}/game/shared/activitylist.cpp
				AlphaMaterialProxy.cpp
				${ROOT_DIR}/game/shared/ammodef.cpp
				AnimatedEntityTextureProxy.cpp
				animatedoffsettextureproxy.cpp
				AnimatedTextureProxy.cpp
				AnimateSpecificTextureProxy.cpp
				${ROOT_DIR}/game/shared/animation.cpp
				${ROOT_DIR}/game/shared/base_playeranimstate.cpp
				${ROOT_DIR}/game/shared/baseachievement.cpp
				${ROOT_DIR}/game/shared/baseachievement.h
				BaseAnimatedTextureProxy.cpp
				baseclientrendertargets.cpp
				${ROOT_DIR}/game/shared/basecombatcharacter_shared.cpp
				${ROOT_DIR}/game/shared/basecombatweapon_shared.cpp
				${ROOT_DIR}/game/shared/baseentity_shared.cpp
				${ROOT_DIR}/game/shared/basegrenade_shared.cpp
				${ROOT_DIR}/game/shared/baseparticleentity.cpp
				${ROOT_DIR}/game/shared/baseplayer_shared.cpp
				${ROOT_DIR}/game/shared/baseviewmodel_shared.cpp
				beamdraw.cpp
				${ROOT_DIR}/game/shared/beam_shared.cpp
				${ROOT_DIR}/public/bone_accessor.cpp
				bone_merge_cache.cpp
				c_AI_BaseHumanoid.cpp
				c_AI_BaseNPC.cpp
				c_baseanimating.cpp
				c_baseanimatingoverlay.cpp
				c_basecombatcharacter.cpp
				c_basecombatweapon.cpp
				c_basedoor.cpp
				c_baseentity.cpp
				c_baseflex.cpp
				c_baseplayer.cpp
				c_baseviewmodel.cpp
				c_breakableprop.cpp
				c_colorcorrection.cpp
				c_colorcorrectionvolume.cpp
				c_dynamiclight.cpp
				c_entitydissolve.cpp
				c_entityparticletrail.cpp
				c_env_fog_controller.cpp
				c_env_global_light.cpp
				c_env_particlescript.cpp
				c_env_projectedtexture.cpp
				c_env_screenoverlay.cpp
				c_env_tonemap_controller.cpp
				c_fire_smoke.cpp
				c_fish.cpp
				c_func_areaportalwindow.cpp
				c_func_breakablesurf.cpp
				c_func_conveyor.cpp
				c_func_dust.cpp
				c_func_lod.cpp
				c_func_occluder.cpp
				c_func_reflective_glass.cpp
				c_func_rotating.cpp
				c_func_smokevolume.cpp
				c_func_tracktrain.cpp
				c_gib.cpp
				c_hairball.cpp
				c_info_overlay_accessor.cpp
				c_lightglow.cpp
				c_lights.cpp
				C_MaterialModifyControl.cpp
				c_particle_system.cpp
				c_physbox.cpp
				c_physicsprop.cpp
				c_physmagnet.cpp
				c_pixel_visibility.cpp
				c_plasma.cpp
				c_playerresource.cpp
				c_point_camera.cpp
				c_point_commentary_node.cpp
				c_props.cpp
				c_props.h
				c_ragdoll_manager.cpp
				c_rope.cpp
				c_rumble.cpp
				c_sceneentity.cpp
				c_shadowcontrol.cpp
				c_slideshow_display.cpp
				c_slideshow_display.h
				c_soundscape.cpp
				c_spotlight_end.cpp
				c_sprite.cpp
				c_sprite_perfmonitor.cpp
				c_sun.cpp
				c_team.cpp
				c_tesla.cpp
				c_test_proxytoggle.cpp
				c_user_message_register.cpp
				c_vehicle_choreo_generic.cpp
				c_vehicle_jeep.cpp
				c_vguiscreen.cpp
				hl2/C_WaterBullet.cpp
				hl2/hud_autoaim.cpp
				C_WaterLODControl.cpp
				c_world.cpp
				CamoMaterialProxy.cpp
				cdll_client_int.cpp
				cdll_bounded_cvars.cpp
				cdll_bounded_cvars.h
				cdll_util.cpp
				cl_mat_stub.cpp
				classmap.cpp
				client_factorylist.cpp
				client_thinklist.cpp
				ClientEffectPrecacheSystem.cpp
				cliententitylist.cpp
				ClientLeafSystem.cpp
				clientmode_shared.cpp
				ClientShadowMgr.cpp
				clientsideeffects.cpp
				clientsideeffects_test.cpp
				colorcorrectionmgr.cpp
				${ROOT_DIR}/game/shared/collisionproperty.cpp
				${ROOT_DIR}/game/shared/death_pose.cpp
				${ROOT_DIR}/game/shared/debugoverlay_shared.cpp
				${ROOT_DIR}/game/shared/decals.cpp
				DetailObjectSystem.cpp
				DummyProxy.cpp
				${ROOT_DIR}/game/shared/effect_dispatch_data.cpp
				EffectsClient.cpp
				${ROOT_DIR}/game/shared/ehandle.cpp
				${ROOT_DIR}/game/shared/entitylist_base.cpp
				entityoriginmaterialproxy.cpp
				${ROOT_DIR}/game/shared/EntityParticleTrail_Shared.cpp
				${ROOT_DIR}/game/shared/env_detail_controller.cpp
				${ROOT_DIR}/game/shared/env_wind_shared.cpp
				${ROOT_DIR}/game/shared/eventlist.cpp
				flashlighteffect.cpp
				${ROOT_DIR}/game/shared/func_ladder.cpp
				FunctionProxy.cpp
				fx_blood.cpp
				fx_cube.cpp
				fx_explosion.cpp
				fx_fleck.cpp
				fx_impact.cpp
				fx_interpvalue.cpp
				fx_quad.cpp
				fx_shelleject.cpp
				fx_staticline.cpp
				fx_tracer.cpp
				fx_trail.cpp
				fx_water.cpp
				${ROOT_DIR}/game/shared/gamemovement.cpp
				${ROOT_DIR}/game/shared/gamerules.cpp
				${ROOT_DIR}/game/shared/gamerules_register.cpp
				${ROOT_DIR}/game/shared/gamestringpool.cpp
				gametrace_client.cpp
				${ROOT_DIR}/game/shared/gamevars_shared.cpp
				glow_overlay.cpp
				${ROOT_DIR}/game/shared/hintmessage.cpp
				${ROOT_DIR}/game/shared/hintsystem.cpp
				hltvcamera.cpp
				hud.cpp
				hud_animationinfo.cpp
				hud_basechat.cpp
				hud_basetimer.cpp
				hud_bitmapnumericdisplay.cpp
				hud_closecaption.cpp
				hud_crosshair.cpp
				hud_element_helper.cpp
				hl2/hud_filmdemo.cpp
				hl2/hud_hdrdemo.cpp
				hud_hintdisplay.cpp
				hud_msg.cpp
				hud_numericdisplay.cpp
				hud_pdump.cpp
				hud_redraw.cpp
				hud_vehicle.cpp
				${ROOT_DIR}/game/shared/igamesystem.cpp
				in_camera.cpp
				in_joystick.cpp
				in_main.cpp
				initializer.cpp
				interpolatedvar.cpp
				IsNPCProxy.cpp
				LampBeamProxy.cpp
				LampHaloProxy.cpp
				${ROOT_DIR}/game/shared/mapentities_shared.cpp
				MathProxy.cpp
				matrixproxy.cpp
				menu.cpp
				message.cpp
				movehelper_client.cpp
				${ROOT_DIR}/game/shared/movevars_shared.cpp
				${ROOT_DIR}/game/shared/multiplay_gamerules.cpp
				${ROOT_DIR}/game/shared/obstacle_pushaway.cpp
				panelmetaclassmgr.cpp
				particle_collision.cpp
				particle_litsmokeemitter.cpp
				${ROOT_DIR}/game/shared/particle_parse.cpp
				${ROOT_DIR}/game/shared/particle_parse.h
				${ROOT_DIR}/game/shared/particle_property.cpp
				${ROOT_DIR}/game/shared/particle_property.h
				particle_proxies.cpp
				particle_simple3D.cpp
				particlemgr.cpp
				particles_attractor.cpp
				particles_ez.cpp
				particles_localspace.cpp
				particles_new.cpp
				particles_simple.cpp
				${ROOT_DIR}/game/shared/particlesystemquery.cpp
				perfvisualbenchmark.cpp
				physics.cpp
				physics_main_client.cpp
				${ROOT_DIR}/game/shared/physics_main_shared.cpp
				${ROOT_DIR}/game/shared/physics_saverestore.cpp
				${ROOT_DIR}/game/shared/physics_shared.cpp
				physpropclientside.cpp
				playerandobjectenumerator.cpp
				${ROOT_DIR}/game/shared/point_bonusmaps_accessor.cpp
				${ROOT_DIR}/game/shared/point_bonusmaps_accessor.h
				${ROOT_DIR}/game/shared/point_posecontroller.cpp
				${ROOT_DIR}/game/shared/precache_register.cpp
				${ROOT_DIR}/game/shared/predictableid.cpp
				prediction.cpp
				${ROOT_DIR}/game/shared/predictioncopy.cpp
				${ROOT_DIR}/game/shared/props_shared.cpp
				proxyentity.cpp
				ProxyHealth.cpp
				proxyplayer.cpp
				proxypupil.cpp
				ragdoll.cpp
				${ROOT_DIR}/game/shared/ragdoll_shared.cpp
				recvproxy.cpp
				${ROOT_DIR}/game/shared/rope_helpers.cpp
				${ROOT_DIR}/game/shared/saverestore.cpp
				${ROOT_DIR}/game/shared/sceneentity_shared.cpp
				ScreenSpaceEffects.cpp
				${ROOT_DIR}/game/shared/sequence_Transitioner.cpp
				simple_keys.cpp
				${ROOT_DIR}/game/shared/simtimer.cpp
				${ROOT_DIR}/game/shared/singleplay_gamerules.cpp
				${ROOT_DIR}/game/shared/SoundEmitterSystem.cpp
				${ROOT_DIR}/game/shared/soundenvelope.cpp
				${ROOT_DIR}/public/SoundParametersInternal.cpp
				statgather.cpp
				splinepatch.cpp
				${ROOT_DIR}/game/shared/Sprite.cpp
				spritemodel.cpp
				${ROOT_DIR}/game/shared/SpriteTrail.cpp
				${ROOT_DIR}/game/shared/studio_shared.cpp
				${ROOT_DIR}/game/shared/takedamageinfo.cpp
				${ROOT_DIR}/game/shared/teamplay_gamerules.cpp
				${ROOT_DIR}/game/shared/teamplayroundbased_gamerules.cpp
				${ROOT_DIR}/game/shared/test_ehandle.cpp
				text_message.cpp
				TextureScrollMaterialProxy.cpp
				TimeMaterialProxy.cpp
				toggletextureproxy.cpp
				${ROOT_DIR}/game/shared/UserCmd.cpp
				${ROOT_DIR}/game/shared/usermessages.cpp
				${ROOT_DIR}/game/shared/util_shared.cpp
				${ROOT_DIR}/game/shared/vehicle_viewblend_shared.cpp
				vgui_avatarimage.cpp
				vgui_avatarimage.h
				vgui_BasePanel.cpp
				vgui_bitmapbutton.cpp
				vgui_bitmapimage.cpp
				vgui_BitmapPanel.cpp
				vgui_CenterStringPanel.cpp
				vgui_ConsolePanel.cpp
				vgui_DebugOverlayPanel.cpp
				vgui_FPSPanel.cpp
				vgui_game_viewport.cpp
				vgui_grid.cpp
				vgui_int.cpp
				vgui_LoadingDiscPanel.cpp
				vgui_MessageChars.cpp
				vgui_NetGraphPanel.cpp
				vgui_slideshow_display_screen.cpp
				view.cpp
				view_beams.cpp
				view_effects.cpp
				view_scene.cpp
				viewangleanim.cpp
				ViewConeImage.cpp
				viewdebug.cpp
				viewdebug.h
				viewpostprocess.cpp
				viewpostprocess.h
				viewrender.cpp
				${ROOT_DIR}/game/shared/voice_banmgr.cpp
				${ROOT_DIR}/game/shared/voice_status.cpp
				warp_overlay.cpp
				WaterLODMaterialProxy.cpp
				${ROOT_DIR}/game/shared/weapon_parse.cpp
				weapon_selection.cpp
				weapons_resource.cpp
				WorldDimsProxy.cpp
				vgui_video.cpp
				${ROOT_DIR}/game/shared/mp_shareddefs.cpp
				${ROOT_DIR}/public/bone_setup.cpp						
				${ROOT_DIR}/public/posedebugger.cpp					
				${ROOT_DIR}/public/client_class.cpp					
				${ROOT_DIR}/common/compiledcaptionswap.cpp			
				${ROOT_DIR}/public/CollisionUtils.cpp			
				${ROOT_DIR}/public/crtmemdebug.cpp					
				${ROOT_DIR}/public/dt_recv.cpp						
				${ROOT_DIR}/public/dt_utlvector_common.cpp			
				${ROOT_DIR}/public/dt_utlvector_recv.cpp				
				${ROOT_DIR}/public/filesystem_helpers.cpp				
				${ROOT_DIR}/public/interpolatortypes.cpp				
				${ROOT_DIR}/game/shared/interval.cpp					
				${ROOT_DIR}/public/networkvar.cpp						
				${ROOT_DIR}/common/randoverride.cpp					
				${ROOT_DIR}/public/rope_physics.cpp					
				${ROOT_DIR}/public/scratchpad3d.cpp					
				${ROOT_DIR}/public/ScratchPadUtils.cpp				
				${ROOT_DIR}/public/sentence.cpp						
				${ROOT_DIR}/game/shared/sheetsimulator.cpp			
				${ROOT_DIR}/public/simple_physics.cpp					
				${ROOT_DIR}/public/stringregistry.cpp					
				${ROOT_DIR}/public/studio.cpp							
				${ROOT_DIR}/public/vallocator.cpp						
				${ROOT_DIR}/public/vgui_controls/vgui_controls.cpp	
				${ROOT_DIR}/public/jigglebones.cpp					
				in_mouse.cpp										
				c_basetempentity.cpp
				c_effects.cpp
				c_impact_effects.cpp
				c_movie_explosion.cpp
				c_particle_fire.cpp
				c_particle_smokegrenade.cpp
				c_prop_vehicle.cpp
				c_recipientfilter.cpp
				c_smoke_trail.cpp
				c_SmokeStack.cpp
				c_steamjet.cpp
				c_stickybolt.cpp
				c_te.cpp
				c_te_armorricochet.cpp
				c_te_basebeam.cpp
				c_te_beamentpoint.cpp
				c_te_beaments.cpp
				c_te_beamfollow.cpp
				c_te_beamlaser.cpp
				c_te_beampoints.cpp
				c_te_beamring.cpp
				c_te_beamringpoint.cpp
				c_te_beamspline.cpp
				c_te_bloodsprite.cpp
				c_te_bloodstream.cpp
				c_te_breakmodel.cpp
				c_te_bspdecal.cpp
				c_te_bubbles.cpp
				c_te_bubbletrail.cpp
				c_te_clientprojectile.cpp
				c_te_decal.cpp
				c_te_dynamiclight.cpp
				c_te_effect_dispatch.cpp
				c_te_energysplash.cpp
				c_te_explosion.cpp
				c_te_fizz.cpp
				c_te_footprint.cpp
				c_te_glassshatter.cpp
				c_te_glowsprite.cpp
				c_te_impact.cpp
				c_te_killplayerattachments.cpp
				c_te_largefunnel.cpp
				c_te_legacytempents.cpp
				c_te_muzzleflash.cpp
				c_te_particlesystem.cpp
				c_te_physicsprop.cpp
				c_te_playerdecal.cpp
				c_te_projecteddecal.cpp
				c_te_showline.cpp
				c_te_smoke.cpp
				c_te_sparks.cpp
				c_te_sprite.cpp
				c_te_spritespray.cpp
				c_te_worlddecal.cpp
				C_TestTraceline.cpp
				c_tracer.cpp
				fx.cpp
				fx_discreetline.cpp
				fx_envelope.cpp
				fx_line.cpp
				fx_sparks.cpp
				ParticleSphereRenderer.cpp
				smoke_fog_overlay.cpp
				game_controls/baseviewport.cpp
				game_controls/ClientScoreBoardDialog.cpp
				game_controls/commandmenu.cpp
				game_controls/intromenu.cpp
				game_controls/MapOverview.cpp
				game_controls/NavProgress.cpp
				game_controls/SpectatorGUI.cpp
				game_controls/teammenu.cpp
				game_controls/vguitextwindow.cpp
				game_controls/IconPanel.cpp
				${ROOT_DIR}/public/tools/bonelist.cpp
				${ROOT_DIR}/public/tools/bonelist.h
				entity_client_tools.cpp
				toolframework_client.cpp
				toolframework_client.h
				mp3player.cpp
				basepresence.cpp
)

set(CLIENT_HL2_FILES
				hud_chat.cpp
				c_team_objectiveresource.cpp
				c_team_objectiveresource.h
				${ROOT_DIR}/game/shared/hl2/basehlcombatweapon_shared.cpp
				${ROOT_DIR}/game/shared/hl2/achievements_hl2.cpp
				hl2/c_antlion_dust.cpp
				hl2/c_ar2_explosion.cpp
				hl2/c_barnacle.cpp
				hl2/c_barney.cpp
				hl2/c_basehelicopter.cpp
				hl2/c_basehelicopter.h
				hl2/c_basehlcombatweapon.cpp
				hl2/c_basehlcombatweapon.h
				hl2/c_basehlplayer.cpp
				hl2/c_basehlplayer.h
				hl2/c_citadel_effects.cpp
				hl2/c_corpse.cpp
				hl2/c_corpse.h
				hl2/c_env_alyxtemp.cpp
				hl2/c_env_headcrabcanister.cpp
				hl2/c_env_starfield.cpp
				hl2/c_func_tankmortar.cpp
				hl2/c_hl2_playerlocaldata.cpp
				hl2/c_hl2_playerlocaldata.h
				hl2/c_info_teleporter_countdown.cpp
				hl2/c_npc_antlionguard.cpp
				hl2/c_npc_combinegunship.cpp
				hl2/c_npc_manhack.cpp
				hl2/c_npc_rollermine.cpp
				hl2/c_plasma_beam_node.cpp
				hl2/c_prop_combine_ball.cpp
				hl2/c_prop_combine_ball.h
				hl2/c_rotorwash.cpp
				hl2/c_script_intro.cpp
				${ROOT_DIR}/game/shared/script_intro_shared.cpp
				hl2/c_strider.cpp
				hl2/c_te_concussiveexplosion.cpp
				hl2/c_te_flare.cpp
				hl2/c_thumper_dust.cpp
				hl2/c_vehicle_airboat.cpp
				hl2/c_vehicle_cannon.cpp
				hl2/c_vehicle_crane.cpp
				hl2/c_vehicle_crane.h
				hl2/c_vehicle_prisoner_pod.cpp
				hl2/c_weapon__stubs_hl2.cpp
				hl2/c_weapon_crossbow.cpp
				hl2/c_weapon_physcannon.cpp
				hl2/c_weapon_stunstick.cpp
				${ROOT_DIR}/game/shared/hl2/citadel_effects_shared.h
				hl2/clientmode_hlnormal.cpp
				hl2/clientmode_hlnormal.h
				death.cpp
				${ROOT_DIR}/game/shared/hl2/env_headcrabcanister_shared.cpp
				${ROOT_DIR}/game/shared/hl2/env_headcrabcanister_shared.h
				hl2/fx_antlion.cpp
				hl2/fx_bugbait.cpp
				hl2/fx_hl2_impacts.cpp
				hl2/fx_hl2_tracers.cpp
				hl2/hl2_clientmode.cpp
				${ROOT_DIR}/game/shared/hl2/hl2_gamerules.cpp
				${ROOT_DIR}/game/shared/hl2/hl2_gamerules.h
				${ROOT_DIR}/game/shared/hl2/hl2_shareddefs.h
				${ROOT_DIR}/game/shared/hl2/hl2_usermessages.cpp
				${ROOT_DIR}/game/shared/hl2/hl_gamemovement.cpp
				${ROOT_DIR}/game/shared/hl2/hl_gamemovement.h
				hl2/hl_in_main.cpp
				hl2/hl_prediction.cpp
				hl2/hud_ammo.cpp
				hl2/hud_battery.cpp
				hl2/hud_blood.cpp
				hl2/hud_credits.cpp
				hl2/hud_damageindicator.cpp
				hl2/hud_flashlight.cpp
				hl2/hud_health.cpp
				hl2/hud_poisondamageindicator.cpp
				hud_posture.cpp
				hl2/hud_quickinfo.cpp
				hud_squadstatus.cpp
				hl2/hud_suitpower.cpp
				hl2/hud_suitpower.h
				hl2/hud_weaponselection.cpp
				hl2/hud_zoom.cpp
				hl2/ShieldProxy.cpp
				hl2/vgui_rootpanel_hl2.cpp
			 	episodic/c_vort_charge_token.cpp
)

set(CLIENT_HL2MP_FILES
				-	${ROOT_DIR}/game/shared/weapon_parse_default.cpp
					c_team_objectiveresource.cpp
					c_team_objectiveresource.h
					hud_voicestatus.cpp
					${ROOT_DIR}/game/shared/predicted_viewmodel.cpp
					${ROOT_DIR}/game/shared/predicted_viewmodel.h
					episodic/c_vort_charge_token.cpp
					${ROOT_DIR}/game/shared/hl2/basehlcombatweapon_shared.cpp
					hl2/c_antlion_dust.cpp
					hl2/c_ar2_explosion.cpp
					hl2/c_barnacle.cpp
					hl2/c_barney.cpp
					hl2/c_basehelicopter.cpp
					hl2/c_basehelicopter.h
					hl2/c_basehlcombatweapon.cpp
					hl2/c_basehlcombatweapon.h
					hl2/c_basehlplayer.cpp
					hl2/c_basehlplayer.h
					hl2/c_citadel_effects.cpp
					hl2/c_corpse.cpp
					hl2/c_corpse.h
					hl2/c_env_alyxtemp.cpp
					hl2/c_env_headcrabcanister.cpp
					hl2/c_env_starfield.cpp
					hl2/c_func_tankmortar.cpp
					hl2/c_hl2_playerlocaldata.cpp
					hl2/c_hl2_playerlocaldata.h
					hl2/c_info_teleporter_countdown.cpp
					hl2/c_npc_antlionguard.cpp
					hl2/c_npc_combinegunship.cpp
					hl2/c_npc_manhack.cpp
					hl2/c_npc_rollermine.cpp
					hl2/c_plasma_beam_node.cpp
					hl2/c_prop_combine_ball.cpp
					hl2/c_prop_combine_ball.h
					hl2/c_rotorwash.cpp
					hl2/c_script_intro.cpp
					${ROOT_DIR}/game/shared/script_intro_shared.cpp
					hl2/c_strider.cpp
					hl2/c_te_concussiveexplosion.cpp
					hl2/c_te_flare.cpp
					hl2/c_thumper_dust.cpp
					hl2/c_vehicle_airboat.cpp
					hl2/c_vehicle_cannon.cpp
					hl2/c_vehicle_crane.cpp
					hl2/c_vehicle_crane.h
					hl2/c_vehicle_prisoner_pod.cpp
					hl2/c_weapon__stubs_hl2.cpp
					hl2/c_weapon_crossbow.cpp
					${ROOT_DIR}/game/shared/hl2/citadel_effects_shared.h
					${ROOT_DIR}/game/shared/hl2/env_headcrabcanister_shared.cpp
					${ROOT_DIR}/game/shared/hl2/env_headcrabcanister_shared.h
					hl2/fx_antlion.cpp
					hl2/fx_bugbait.cpp
					hl2/fx_hl2_impacts.cpp
					hl2/fx_hl2_tracers.cpp
					hl2/hl2_clientmode.cpp
					${ROOT_DIR}/game/shared/hl2/hl2_gamerules.cpp
					${ROOT_DIR}/game/shared/hl2/hl2_gamerules.h
					${ROOT_DIR}/game/shared/hl2/hl2_shareddefs.h
					${ROOT_DIR}/game/shared/hl2/hl2_usermessages.cpp
					${ROOT_DIR}/game/shared/hl2/hl_gamemovement.cpp
					${ROOT_DIR}/game/shared/hl2/hl_gamemovement.h
					hl2/hl_in_main.cpp
					hl2/hl_prediction.cpp
					hl2/hud_ammo.cpp
					hl2/hud_battery.cpp
					hl2/hud_blood.cpp
					hl2/hud_credits.cpp
					hl2/hud_damageindicator.cpp
					hl2/hud_flashlight.cpp
					hl2/hud_health.cpp
					hl2/hud_poisondamageindicator.cpp
					hl2/hud_quickinfo.cpp
					hud_squadstatus.cpp
					hl2/hud_suitpower.cpp
					hl2/hud_suitpower.h
					hl2/hud_weaponselection.cpp
					hl2/hud_zoom.cpp
					hl2/ShieldProxy.cpp
					hl2/vgui_rootpanel_hl2.cpp
					hl2mp/c_hl2mp_player.cpp
					hl2mp/c_hl2mp_player.h
					hl2mp/c_te_hl2mp_shotgun_shot.cpp
					hl2mp/clientmode_hl2mpnormal.cpp
					hl2mp/clientmode_hl2mpnormal.h
					${ROOT_DIR}/game/shared/hl2mp/hl2mp_gamerules.cpp
					${ROOT_DIR}/game/shared/hl2mp/hl2mp_gamerules.h
					${ROOT_DIR}/game/shared/hl2mp/hl2mp_player_shared.cpp
					${ROOT_DIR}/game/shared/hl2mp/hl2mp_player_shared.h
					${ROOT_DIR}/game/shared/hl2mp/hl2mp_weapon_parse.cpp
					${ROOT_DIR}/game/shared/hl2mp/hl2mp_weapon_parse.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_357.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_ar2.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_ar2.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_crossbow.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_crowbar.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_frag.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_hl2mpbase.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_hl2mpbase.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_hl2mpbase_machinegun.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_hl2mpbase_machinegun.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_hl2mpbasebasebludgeon.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_hl2mpbasehlmpcombatweapon.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_hl2mpbasehlmpcombatweapon.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_physcannon.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_physcannon.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_pistol.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_rpg.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_rpg.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_shotgun.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_slam.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_slam.h
					${ROOT_DIR}/game/shared/hl2mp/weapon_smg1.cpp
					${ROOT_DIR}/game/shared/hl2mp/weapon_stunstick.cpp
					hl2mp/ui/backgroundpanel.cpp
					hl2mp/ui/backgroundpanel.h
					hl2mp/hl2mp_hud_chat.cpp
					hl2mp/hl2mp_hud_chat.h
					hl2mp/hl2mp_hud_target_id.cpp
					hl2mp/hl2mp_hud_team.cpp
					hl2mp/ui/hl2mpclientscoreboard.cpp
					hl2mp/ui/hl2mpclientscoreboard.h
					hl2mp/ui/hl2mptextwindow.cpp
					hl2mp/ui/hl2mptextwindow.h
					hl2mp/hud_deathnotice.cpp
)

set(CLIENT_EP1_FILES
				hud_chat.cpp
				c_team_objectiveresource.cpp
				c_team_objectiveresource.h
				${ROOT_DIR}/game/shared/hl2/basehlcombatweapon_shared.cpp
				${ROOT_DIR}/game/shared/episodic/achievements_ep1.cpp
				${ROOT_DIR}/game/shared/episodic/achievements_ep2.cpp
				${ROOT_DIR}/game/shared/episodic/achievements_epx.cpp
				hl2/c_antlion_dust.cpp
				hl2/c_ar2_explosion.cpp
				hl2/c_barnacle.cpp
				hl2/c_barney.cpp
				hl2/c_basehelicopter.cpp
				hl2/c_basehelicopter.h
				hl2/c_basehlcombatweapon.cpp
				hl2/c_basehlcombatweapon.h
				hl2/c_basehlplayer.cpp
				hl2/c_basehlplayer.h
				hl2/c_citadel_effects.cpp
				hl2/c_corpse.cpp
				hl2/c_corpse.h
				hl2/c_env_alyxtemp.cpp
				hl2/c_env_headcrabcanister.cpp
				hl2/c_env_starfield.cpp
				hl2/c_func_tankmortar.cpp
				hl2/c_hl2_playerlocaldata.cpp
				hl2/c_hl2_playerlocaldata.h
				hl2/c_info_teleporter_countdown.cpp
				hl2/c_npc_antlionguard.cpp
				hl2/c_npc_combinegunship.cpp
				hl2/c_npc_manhack.cpp
				hl2/c_npc_rollermine.cpp
				hl2/c_plasma_beam_node.cpp
				hl2/c_prop_combine_ball.cpp
				hl2/c_prop_combine_ball.h
				episodic/c_prop_scalable.cpp
				hl2/c_rotorwash.cpp
				hl2/c_script_intro.cpp
				${ROOT_DIR}/game/shared/script_intro_shared.cpp
				hl2/c_strider.cpp
				hl2/c_te_concussiveexplosion.cpp
				hl2/c_te_flare.cpp
				hl2/c_thumper_dust.cpp
				hl2/c_vehicle_airboat.cpp
				hl2/c_vehicle_cannon.cpp
				hl2/c_vehicle_crane.cpp
				hl2/c_vehicle_crane.h
				episodic/c_vehicle_jeep_episodic.cpp
				hl2/c_vehicle_prisoner_pod.cpp
				episodic/c_vort_charge_token.cpp
				hl2/c_weapon__stubs_hl2.cpp
				hl2/c_weapon_crossbow.cpp
				episodic/c_weapon_hopwire.cpp
				hl2/c_weapon_physcannon.cpp
				hl2/c_weapon_stunstick.cpp
				${ROOT_DIR}/game/shared/hl2/citadel_effects_shared.h
				hl2/clientmode_hlnormal.cpp
				hl2/clientmode_hlnormal.h
				death.cpp
				${ROOT_DIR}/game/shared/hl2/env_headcrabcanister_shared.cpp
				${ROOT_DIR}/game/shared/hl2/env_headcrabcanister_shared.h
				${ROOT_DIR}/game/shared/episodic/npc_advisor_shared.h
				episodic/c_npc_advisor.cpp
				episodic/episodic_screenspaceeffects.cpp
				episodic/episodic_screenspaceeffects.h
				episodic/flesh_internal_material_proxy.cpp
				hl2/fx_antlion.cpp
				hl2/fx_bugbait.cpp
				hl2/fx_hl2_impacts.cpp
				hl2/fx_hl2_tracers.cpp
				hl2/hl2_clientmode.cpp
				${ROOT_DIR}/game/shared/hl2/hl2_gamerules.cpp
				${ROOT_DIR}/game/shared/hl2/hl2_gamerules.h
				${ROOT_DIR}/game/shared/hl2/hl2_shareddefs.h
				${ROOT_DIR}/game/shared/hl2/hl2_usermessages.cpp
				${ROOT_DIR}/game/shared/hl2/hl_gamemovement.cpp
				${ROOT_DIR}/game/shared/hl2/hl_gamemovement.h
				hl2/hl_in_main.cpp
				hl2/hl_prediction.cpp
				hl2/hud_ammo.cpp
				hl2/hud_battery.cpp
				hl2/hud_blood.cpp
				hl2/hud_credits.cpp
				hl2/hud_damageindicator.cpp
				hl2/hud_flashlight.cpp
				hl2/hud_locator.cpp
				hl2/hud_health.cpp
				hl2/hud_poisondamageindicator.cpp			
				hud_posture.cpp
				hl2/hud_quickinfo.cpp
				hl2/hud_radar.cpp
				hl2/hud_radar.h
				hud_squadstatus.cpp
				hl2/hud_suitpower.cpp
				hl2/hud_suitpower.h
				hl2/hud_weaponselection.cpp
				hl2/hud_zoom.cpp
				hl2/ShieldProxy.cpp
				${ROOT_DIR}/game/shared/hl2/survival_gamerules.cpp
				hl2/vgui_rootpanel_hl2.cpp
				episodic/c_npc_puppet.cpp
)
