//===== Copyright © 1996-2005, Valve Corporation, All rights reserved. ======//
//
// Purpose: defines constants to use for the materialsystem and shaderapi
// SetxxxRenderingParameter functions
//
// $NoKeywords: $
//
//===========================================================================//

#ifndef RENDERPARM_H
#define RENDERPARM_H

#ifndef _WIN32
#pragma once
#endif

#define MAX_FLOAT_RENDER_PARMS 20
//#define MAX_VECTOR_RENDER_PARMS 20

enum RenderParamVector_t
{
	VECTOR_RENDERPARM_GSTRING_CASCADED_FORWARD,
	VECTOR_RENDERPARM_GSTRING_CASCADED_STEP,
	VECTOR_RENDERPARM_GSTRING_CASCADED_AMBIENT_MIN,
	VECTOR_RENDERPARM_GSTRING_CASCADED_AMBIENT_DELTA,

	MAX_VECTOR_RENDER_PARMS = 20
};

enum RenderParamInt_t
{
	INT_RENDERPARM_ENABLE_FIXED_LIGHTING = 0,
	INT_RENDERPARM_MORPH_ACCUMULATOR_X_OFFSET,
	INT_RENDERPARM_MORPH_ACCUMULATOR_Y_OFFSET,
	INT_RENDERPARM_MORPH_ACCUMULATOR_SUBRECT_WIDTH,
	INT_RENDERPARM_MORPH_ACCUMULATOR_SUBRECT_HEIGHT,
	INT_RENDERPARM_MORPH_ACCUMULATOR_4TUPLE_COUNT,

	INT_RENDERPARM_MORPH_WEIGHT_X_OFFSET,
	INT_RENDERPARM_MORPH_WEIGHT_Y_OFFSET,
	INT_RENDERPARM_MORPH_WEIGHT_SUBRECT_WIDTH,
	INT_RENDERPARM_MORPH_WEIGHT_SUBRECT_HEIGHT,

	INT_RENDERPARM_WRITE_DEPTH_TO_DESTALPHA,

	// idk
	INT_RENDERPARM_BACK_BUFFER_INDEX,
	INT_FLASHLIGHT_DEPTHTEXTURE_FALLBACK_FIRST,
	INT_FLASHLIGHT_DEPTHTEXTURE_FALLBACK_LAST = INT_FLASHLIGHT_DEPTHTEXTURE_FALLBACK_FIRST + 4,
	// CSM
	INT_CASCADED_DEPTHTEXTURE,
	INT_CASCADED_MATRIX_ADDRESS_0,

	MAX_INT_RENDER_PARMS = 20
};

enum RenderParamFloat_t
{
	FLOAT_RENDERPARM_MINIMUMLIGHTING = 0,

	//MAX_FLOAT_RENDER_PARM = 20
};

#endif // RENDERPARM_H
