#ifndef COMMON_CBUFFERS_DEF_H_
#define COMMON_CBUFFERS_DEF_H_

#include "common_cbuffers_fxc.h"

CBUFFER_PERMATERIAL( INTERNAL_CBUFFER_REG_0 )
CBUFFER_PERMODEL( INTERNAL_CBUFFER_REG_1 )
CBUFFER_PERFRAME( INTERNAL_CBUFFER_REG_2 )
CBUFFER_PERSCENE( INTERNAL_CBUFFER_REG_3 )
CBUFFER_SKINNING( INTERNAL_CBUFFER_REG_4 )

#endif // COMMON_CBUFFERS_DEF_H_