default:  fxctmp9_tmp\bik_vs40.inc shaders\fxc\bik_vs40.vcs fxctmp9_tmp\bik_ps40.inc shaders\fxc\bik_ps40.vcs

fxctmp9_tmp\bik_vs40.inc shaders\fxc\bik_vs40.vcs: bik_vs40.fxc common_pragmas.h common_hlsl_cpp_consts.h common_fxc.h common_vs_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." bik_vs40.fxc-----bik_vs40
	echo bik_vs40.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt

fxctmp9_tmp\bik_ps40.inc shaders\fxc\bik_ps40.vcs: bik_ps40.fxc common_pragmas.h common_hlsl_cpp_consts.h common_fxc.h common_ps_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." bik_ps40.fxc-----bik_ps40
	echo bik_ps40.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

