default:  fxctmp9_tmp\bik_vs40.inc shaders\fxc\bik_vs40.vcs fxctmp9_tmp\bik_ps40.inc shaders\fxc\bik_ps40.vcs fxctmp9_tmp\unlitgeneric_ps40.inc shaders\fxc\unlitgeneric_ps40.vcs fxctmp9_tmp\unlitgeneric_vs40.inc shaders\fxc\unlitgeneric_vs40.vcs fxctmp9_tmp\wireframe_ps40.inc shaders\fxc\wireframe_ps40.vcs fxctmp9_tmp\wireframe_vs40.inc shaders\fxc\wireframe_vs40.vcs

fxctmp9_tmp\bik_vs40.inc shaders\fxc\bik_vs40.vcs: bik_vs40.fxc shader_register_map.h common_vs_fxc.h common_hlsl_cpp_consts.h common_fxc.h common_pragmas.h common_cbuffers.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." bik_vs40.fxc-----bik_vs40
	echo bik_vs40.fxc>> filestocopy.txt
	echo shader_register_map.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_cbuffers.h>> filestocopy.txt

fxctmp9_tmp\bik_ps40.inc shaders\fxc\bik_ps40.vcs: bik_ps40.fxc shader_register_map.h common_hlsl_cpp_consts.h common_ps_fxc.h common_fxc.h common_pragmas.h common_cbuffers.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." bik_ps40.fxc-----bik_ps40
	echo bik_ps40.fxc>> filestocopy.txt
	echo shader_register_map.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_cbuffers.h>> filestocopy.txt

fxctmp9_tmp\unlitgeneric_ps40.inc shaders\fxc\unlitgeneric_ps40.vcs: unlitgeneric_ps40.fxc common_ps_fxc.h common_hlsl_cpp_consts.h common_fxc.h shader_register_map.h common_cbuffers.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." unlitgeneric_ps40.fxc-----unlitgeneric_ps40
	echo unlitgeneric_ps40.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo shader_register_map.h>> filestocopy.txt
	echo common_cbuffers.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\unlitgeneric_vs40.inc shaders\fxc\unlitgeneric_vs40.vcs: unlitgeneric_vs40.fxc common_hlsl_cpp_consts.h common_fxc.h common_vs_fxc.h shader_register_map.h common_cbuffers.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." unlitgeneric_vs40.fxc-----unlitgeneric_vs40
	echo unlitgeneric_vs40.fxc>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo shader_register_map.h>> filestocopy.txt
	echo common_cbuffers.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\wireframe_ps40.inc shaders\fxc\wireframe_ps40.vcs: wireframe_ps40.fxc common_ps_fxc.h common_hlsl_cpp_consts.h common_fxc.h shader_register_map.h common_cbuffers.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." wireframe_ps40.fxc-----wireframe_ps40
	echo wireframe_ps40.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo shader_register_map.h>> filestocopy.txt
	echo common_cbuffers.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\wireframe_vs40.inc shaders\fxc\wireframe_vs40.vcs: wireframe_vs40.fxc common_cbuffers.h common_pragmas.h shader_register_map.h common_vs_fxc.h common_hlsl_cpp_consts.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." wireframe_vs40.fxc-----wireframe_vs40
	echo wireframe_vs40.fxc>> filestocopy.txt
	echo common_cbuffers.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo shader_register_map.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

